add model specs, add model validations
learn-academy-2022-bravo/cat-tinder-backend-neco-zane pull request #3
Opened 2022-05-13 18:43 UTC by zmprunella

2022-05-13 18:57 UTC, WalkerTexas-coder submitted a review, later dismissed
Check out my feedback!

2022-05-13 18:57 UTC, WalkerTexas-coder commented on spec/models/cat_spec.rb
> +    expect(cat.errors[:enjoys]).to_not be_empty
Let's add the spec for image and for enjoys length

2022-05-13 18:57 UTC, WalkerTexas-coder commented on spec/requests/cats_spec.rb
> +  describe "meaningful status codes" do
Yea?

2022-05-13 18:57 UTC, WalkerTexas-coder commented on spec/requests/cats_spec.rb
> +    end
Missing 3 other request specs

2022-05-13 18:57 UTC, WalkerTexas-coder commented on spec/requests/cats_spec.rb
> +    end
Missing the request aspect of this spec. This looks like it belongs in the models/spec

2022-05-13 21:17 UTC, elysemontano requested changes
You should be checking validations on each attribute in your request spec as well.  Think about what you are testing against.  When testing validations, you will need to consider what error code you get back if you try to create a cat without that attribute.

2022-05-13 21:17 UTC, elysemontano commented on spec/requests/cats_spec.rb
> +  describe "meaningful status codes" do
Would recommend a more descriptive name for your test here.  More specifically than status codes, what is your intent with these tests?

2022-05-14 00:23 UTC, elysemontano requested changes
Almost there, left a few more comments.

2022-05-14 00:23 UTC, elysemontano commented on spec/models/cat_spec.rb
> +      cat = Cat.create name: 'Toasty', age: 2
This cat should enjoy something.

2022-05-14 00:23 UTC, elysemontano commented on spec/requests/cats_spec.rb
> +  describe "can request validation" do
Much better naming convention!  I don't see request validations for age, enjoys, and image.

2022-05-16 15:25 UTC, elysemontano approved these changes
Looks good!

2022-05-16 16:17 UTC, merged